### ISSUE TITLE
Error Installing Template

### ISSUE THREAD

**Issue by scottkuhl** [tesar-tech/BlazorStatic#35]
I just tried to install the template using this command (on MacOS):

`dotnet new install BlazorStatic.Templates`

Which produced the following error:

```
Error: The template 'BlazorStatic Minimal Blog Site Template' (BlazorStatic.Templates) has the following validation errors:
   [Error][MV012] Source './BlazorStaticMinimalBlog' in template does not exist.
Error: Failed to load the template 'BlazorStatic Minimal Blog Site Template' (BlazorStatic.Templates): the template is not valid.
No templates were found in the package BlazorStatic.Templates::1.0.1.
```

**Comment by tesar-tech** [comment]
Thank you for the error report. 

It's a stupid bug.

I think it is caused by the fact that the actual template (`'./BlazorStaticMinimalBlog'`) is a git submodule, which isn't initialized in github action. The template existence is fairly new thing I didn't even wrote release note about.

Fix is easy (hopefully).

I will let you know once it's done.

**Comment by tesar-tech** [comment]
Done. Template version 1.0.2
Please let me know if it works for you.

**Comment by scottkuhl** [comment]
Fixed.  Thanks.  Closing the issue.
